### ISSUE TITLE
"Add to dictionary" is missing

### ISSUE THREAD

**Issue by sojusnik** [Crissium/zim-multilingual-spellchecker#3]
When a word is underlined, then you can't add it to the dictionary, so that it will be recognized as correct in the future. Even if only one dictionary is enabled, the entry for adding a new word to the dictionary is missing.

When implementing this feature, there should be an extra entry in the right-click menu to which dictionary the new word has to be added, because with this wonderful plugin usually several languages are active at the same time.

**Comment by sojusnik** [comment]
Awesome!

In Zim such additions were added to the corresponding files in ~/.config/enchant, regardless of using gtkspell or gtkspellcheck.

**Comment by Crissium** [comment]
This feature has been implemented.

By the way I finally got what you meant by 'not checking live.' Turns out that after changing pages the spellchecker seems to have 'died.' This is a critical bug and is probably caused by my wrong usage of GTK (I have very limited experience with the library). At the moment I worked around the bug with a very ugly hack. Will check it later when I have more time.
